---
# Default vars for chkp_add_sg_cluster role
# Credentials for cp_mgmt* modules and Settings for the Check Point httpapi plugin that provides methods to connect to Checkpoint devices over a HTTP(S)-based api.
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: False
ansible_network_os: checkpoint
ansible_checkpoint_domain: System Data
ansible_user: admin
ansible_ssh_pass: admin

# mgmt_api credentials, server and base URL
mgmt_user: "{{ lookup('env','TF_VAR_mgmt_api_user') }}"
mgmt_password: "{{ lookup('env','TF_VAR_mgmt_api_password') }}"
mgmt_server: "{{ansible_host}}" # This should be your Check Point SMS or MDS
mgmt_api_url: /web_api
mgmt_validate_cert: false

# Mapping mgmt_api var to default var used in the tasks
api_user: "{{mgmt_user}}"
api_password: "{{mgmt_password}}"
api_server: "{{mgmt_server}}"
api_base_url: "{{mgmt_api_url}}"
api_validate_cert: "{{mgmt_validate_cert}}"

