---
# Default vars for chkp_add_sg_cluster role
# Credentials for cp_mgmt* modules and Settings for the Check Point httpapi plugin that provides methods to connect to Checkpoint devices over a HTTP(S)-based api.
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: False
ansible_network_os: check_point.mgmt.checkpoint
ansible_checkpoint_domain: SMC User
ansible_user: "{{ lookup('env','TF_VAR_mgmt_api_user') }}"
ansible_ssh_pass: "{{ lookup('env','TF_VAR_mgmt_api_password') }}"

# mgmt_api credentials, server and base URL
mgmt_user: "{{ lookup('env','TF_VAR_mgmt_api_user') }}"
mgmt_password: "{{ lookup('env','TF_VAR_mgmt_api_password') }}"
mgmt_server: "{{ansible_host}}" # This should be your Check Point SMS or MDS
mgmt_api_url: /web_api
mgmt_validate_cert: false

# Mapping mgmt_api var to default var used in the tasks
api_user: "{{mgmt_user}}"
api_password: "{{mgmt_password}}"
api_server: "{{mgmt_server}}"
api_base_url: "{{mgmt_api_url}}"
api_validate_cert: "{{mgmt_validate_cert}}"

# Check Point Cluster vars
cluster_name : "Ansible_Cluster"
cluster_primary_ip: "10.2.0.193"
cluster_mode : "cluster-xl-ha"
cluster_version : "R80.30"
cluster_eth0_ip : "10.2.0.193"
cluster_eth0_length : 24
cluster_eth0_topology : "EXTERNAL"
cluster_eth0_type : "cluster"
cluster_eth1_ip : "192.168.101.1"
cluster_eth1_length : 24
cluster_eth1_topology : "INTERNAL"
cluster_eth1_type : "cluster"
cluster_eth2_topology : "INTERNAL"
cluster_eth2_type : "sync"
mem1_name : "member1"
mem1_sic : "vpn123"
mem1_eth0_ip : "10.2.0.194"
mem1_eth0_length : 24
mem1_eth1_ip : "192.168.101.2"
mem1_eth1_length : 24
mem1_eth2_ip : "192.168.102.2"
mem1_eth2_length : 24
mem2_name : "member2"
mem2_sic : "vpn123"
mem2_eth0_ip : "10.2.0.195"
mem2_eth0_length : 24
mem2_eth1_ip : "192.168.101.3"
mem2_eth1_length : 24
mem2_eth2_ip : "192.168.102.3"
mem2_eth2_length : 24