---
# Default vars for chkp_add_lsm_gw role
# Credentials for cp_mgmt* modules and Settings for the Check Point httpapi plugin that provides methods to connect to Checkpoint devices over a HTTP(S)-based api.
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: False
ansible_network_os: check_point.mgmt.checkpoint
ansible_checkpoint_domain: SMC User
ansible_user: "{{ lookup('env','TF_VAR_mgmt_api_user') }}"
ansible_password: "{{ lookup('env','TF_VAR_mgmt_api_password') }}"

# Deafult target for run-scrip api call used to execute LSMcli
mgmt_server_name: sms62

# List of gateway objects to add
cp_mgmt_lsm_gateway:
- { state: present, hw: 1570/1590, name: "{{ vm_name }}", lsm_profile: sg1500profile, sickey: vpn123, gw_version: R80.30, co_name: aws_sg03 }


### TEST ###
## Default vars for LSMcli command
#state: present
#hw: 1570/1590
#lsm_profile: sg1500profile
#sickey: vpn123
#co_name: aws_sg03
#
## List of gateway objects to add
#cp_mgmt_lsm_gateway:
#- { ignore_errors: "no", script: "LSMcli {{ ansible_host }} {{ ansible_user }} {{ ansible_password }} Show -N={{ vm_name }}  -F=n" }
#- { ignore_errors: "no", script: "LSMcli {{ ansible_host }} {{ ansible_user }} {{ ansible_password }} AddROBO {{ hw }} {{ vm_name }} {{ lsm_profile }}" }