---
## Run with extra vars for example: 
# ansible-playbook 7_chkp_create_vnf_cloudguard_edge.yml -e "dms_ip=192.168.233.11 mgmt_server_name=nordics-dms11 ansible_checkpoint_domain=nordics"
##Required vars
# dms_ip=[DMS / SMS IP]
# mgmt_server_name=[DMS / SMS objectname]
## Optional var
# ansible_checkpoint_domain=[domain name]
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.hostname }}"
        ansible_host: "{{ dms_ip }}"
        groups: chkp
        vm_name: "{{ item.hostname }}"
        vm_template: cloud02_cgedge_r80dot20
        esxi_hostname: cloud02.local
      with_items:
      - { hostname: vnf01, groups: domains }
      - { hostname: vnf02, groups: domains }
      - { hostname: vnf03, groups: domains }
      - { hostname: vnf04, groups: domains }
      - { hostname: vnf05, groups: domains }

- name:  Add and config CG edge
  hosts: chkp
  gather_facts: no
  roles:
  - role: ../../roles/vm_ware_deploy_instance
    connection: httpapi
  - role: ../../roles/chkp_lsm_gw
    connection: httpapi
    state: present
  - role: ../../roles/chkp_config_gaia_embedded
    connection: ssh
    #ansible_user: api_user # Needed on for my ansible install on Dell . Fix ME!! bug!!
