#  description = "Setting this name for the new Gaia instance "
vsphere_virtual_machine_vm = "mds10"
#  description = "Setting this IP for the new Gaia instance "
gaia_instance_target = "192.168.233.10"
#  description = "Setting Gaia instance type. Accepted values are: primary_mds, secondary_mds, mdls, primary_sms, secondary_sms, ls_se, smsg, sg"
gaia_instance_type = "primary_mds"