#  description = "Setting this IP for the new Gaia instance "
vsphere_virtual_machine_vm = "tfmds20"
#  description = "Setting this IP for the new Gaia instance "
gaia_instance_target = "192.168.233.20"
#  description = "Setting Gaia instance type. Accepted values are: primary_mds, secondary_mds, mdls, primary_sms, secondary_sms, ls_se, smsg, sg"
gaia_instance_type = "secondary_mds"