variable "vsphere_user" {
  type = string
}

variable "vsphere_password" {
  type = string
}

variable "vsphere_server" {
  type = string
}

variable "vsphere_datacenter" {
  type = string
  default = "DC_POC_Lab"
}

variable "vsphere_datastore" {
  type = string
  default = "datastore1"
}

variable "vsphere_host" {
  type = string
  default = "172.23.23.44"
}

variable "mgmt_net" {
  description = "The virtual network for Check Point management traffic"
  default     = "Internal_1"
}

variable "remote_ovf_url" {
  type = string
  default = "http://192.168.100.53" 
}

variable "vsphere_folder_name" {
  type = string
  default = "automation-poc"
}

// -- Check Point configuration --
variable "chkp_otp_key" {
  description = "Used for SIC one time password and admin password"
  type = string
}

variable "chkp_passwd_hash" {
  description = "Password hash for ansible user password, this can be generated by using 'cpopenssl passwd -6 -salt UAxWXDhef2zm8mqt yourpassword'"
  type = string
}

variable "chkp_ftp_user_pwd" {
  description = "Used by Check Point update agent to connect to FTP server for hotfix retrival"
  type = string
}
