- name: "Unclaim GAiA gateway {{zt_gateway_mac}}"
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/unclaim-gaia-gateway"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     headers :
       X-chkp-sid : "{{ sid }}"
     body_format: json
     body:
           '{ 
              "mac"        : "{{zt_gateway_mac}}", 
              "account-id" : "{{datasource_zt_account_id}}" 
            }'
#     status_code: 200, 500