---
- name: Login
  uri:
     url: "https://{{ gaia_server }}/gaia_api/login"
     validate_certs: false
     method: POST
     body_format: json
     body: "{ \"user\" : \"{{ gaia_user }}\", \"password\" : \"{{ gaia_password }}\" }"
  register: loginoutput

- set_fact:
     sid: "{{ loginoutput.json.sid }}"