---
#- include_tasks: gaia_api_check_status.yml
#  when: ansible_checkpoint_domain != "System Data"
#- include_tasks: gaia_api_login.yml
#  when: ansible_checkpoint_domain != "System Data"
#- include_tasks: gaia_api_set_mgmt_api.yml
#  when: ansible_checkpoint_domain != "System Data"
#- include_tasks: gaia_api_logout.yml
#  when: ansible_checkpoint_domain != "System Data"
- include_tasks: cp_mgmt_package.yml
  when: ansible_checkpoint_domain != "System Data"
- include_tasks: cp_mgmt_group.yml
  when: ansible_checkpoint_domain != "System Data"
- include_tasks: cp_mgmt_network.yml
  when: ansible_checkpoint_domain != "System Data"
- include_tasks: cp_mgmt_host.yml
  when: ansible_checkpoint_domain != "System Data"
- include_tasks: cp_mgmt_access_rule.yml
  when: ansible_checkpoint_domain != "System Data"
- include_tasks: cp_mgmt_publish.yml
