---
 - name: Publish
   uri:
      url: "https://{{ api_server }}{{ api_base_url }}/publish"
      validate_certs: "{{ api_validate_cert }}"
      method: POST
      body_format: json
      body: '{}'
      headers : 
        X-chkp-sid : "{{ sid }}"
   register: taskid

 - set_fact:
      task: "{{ taskid.json['task-id'] }}"

 - name: Check Publish Task Progress 
   uri:
      url: "https://{{ api_server }}{{ api_base_url }}/show-task"
      validate_certs: "{{ api_validate_cert }}"
      method: POST
      body_format: json
      body: 
            '{ 
              "task-id" :  "{{task}}" 
             }'
      headers:
        X-chkp-sid : "{{ sid }}"
   retries: 20
   delay: 3
   register: taskoutput
   until: taskoutput.json.tasks[0]['progress-percentage'] == 100