---
- name: Login
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/login"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     body: 
           '{ 
              "user"     : "{{ api_user }}", 
              "password" : "{{ api_password }}", 
              "domain"   :  "{{ ansible_checkpoint_domain }}"
            }'
  register: loginoutput

- set_fact:
     sid: "{{ loginoutput.json.sid }}"

- debug:
    msg: "{{ loginoutput.json.sid }}"