---
 - name: Logout
   uri:
      url: "https://{{ api_server }}{{ api_base_url }}/logout"
      validate_certs: "{{ api_validate_cert }}"
      method: POST
      body_format: json
      body: '{}'
      headers : 
        X-chkp-sid : "{{ sid }}"