---
- name: "show claimed gaia gateway"
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/show-gaia-claimed-gateway"
     validate_certs: true
     method: POST
     headers :
       X-chkp-sid : "{{ sid }}"
     body_format: json
     body: '{ 
              "mac"        : "{{zt_gateway_mac}}", 
              "account-id" : "{{datasource_zt_account_id}}" 
            }'
 
  register: datasource_claimed_gaia_gateway

- debug:
    msg="{{ datasource_claimed_gaia_gateway }}"