---
- name:  "Clone {{ vm_name }} from gaia template and customize"
  vmware_guest:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    validate_certs: no
    datacenter: "{{ vsphere_datacenter }}"
    state: poweredon
    folder: "/cplab"
    template: "{{ vm_template }}"
    name: "{{ vm_name }}"
    esxi_hostname: "{{ esxi_hostname }}"
    linked_clone: yes
    snapshot_src: "{{ vm_snapshot }}"
  delegate_to: localhost