- name: Task for Finance
  cp_mgmt_security_zone:
    name: Finance
    comments: ''
    color: black
    tags: []
    state: '{{state}}'
    ignore_warnings: false
    ignore_errors: false
    wait_for_task: true
    wait_for_task_timeout: '30'
