# Run with extra vars for example: -e "vm_name=mds10 to remove the virtual machine mds10
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: ../roles/inventory

- name: Remove gaia instance from vSphere
  hosts:
  - mdsm
  - sg
  connection: local
  gather_facts: no
  roles:
    - role: ../roles/vm_ware_remove_instance