# Deploys a new machine as Security Gateway and configures it in the specified domain (default domanin is SMC User)
## ansible-playbook primary_sms_create.yml -e "vm_name=smxx target=192.168.233.xx nr=xx" -i smxx,192.168.233.yy,
# Avaliable Options 
## type= primary_mds, secondary_mds, mdls, primary_sms, secondary_sms, ls_se, smsg, sg
## esxi_hostname= cloud03.local, cloud02.local
## vm_template= vm_template= cloud03_r81dot10, cloud02_r81dot10, cloud02_r80dot40, cloud03_r80dot40
## gaia_password: xxxxx

- name:  Add Gaia Instance and run FTW
  hosts: "{{ vm_name }}"
  connection: local
  gather_facts: no
  roles:
  - role: ../roles/vm_ware_deploy_instance
    delegate_to: localhost
  - role: ../roles/chkp_config_gaia
    vars:
      type: primary_sms
      esxi_hostname: cloud03.local
      vm_template: cloud03_r81dot10

#- name:  Add gateway to domain or sms
#  hosts: "{{ sms_ip }}"
#  connection: httpapi
#  gather_facts: no
#  roles:
#    - role: ../roles/chkp_add_sg
#      vars:
#        type: primary_sms