---
# Run with extra vars for example: 
## ansible-playbook vm_ware_gaia_instance_create.yml -e "vm_name=sms69 target=192.168.233.69 type=primary_sms nr=69 vm_template=cloud03_r81_t392"
# Avaliable Options 
## type= primary_mds, secondary_mds, mdls, primary_sms, secondary_sms, ls_se, smsg, sg
## esxi_hostname= cloud03.local, cloud02.local
## vm_template= vm_template= cloud03_r81dot10, cloud03_r81_t392, cloud02_r80dot40, cloud03_r80dot40
## gaia_password: xxxxx
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ vm_name }}"
        ansible_host: "{{target}}"
        groups: chkp
        vm_name: "{{ vm_name }}"
        target: "{{ target }}"
        type: "{{ type }}"

- name:  Add Gaia Instance and run FTW
  hosts: "{{ vm_name }}"
  connection: local
  gather_facts: no
  roles:
  - role: ../roles/vm_ware_deploy_instance
    delegate_to: localhost
  - role: ../roles/chkp_config_gaia