# Run with extra vars for example: 
# ansible-playbook vm_ware_destroy_instance.yml -e "vm_name=mds10" 
# to remove the virtual machine mds10
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ vm_name }}"

- name: Remove gaia instance from vSphere
  hosts: "{{ vm_name }}"
  connection: local
  gather_facts: no
  roles:
    - role: ../roles/vm_ware_remove_instance