---
- name: Check for Secondary MDS OR MDLS objects
  connection: httpapi
  checkpoint_object_facts:
    object_filter: mds20 OR mdls30
  register: datasource_MDS_MDLS

- name: Create MDS & MDLS if it does not exist
  block:

  - name: "Add MDS object"
    uri:
       url: "https://{{ api_server }}{{ api_base_url }}/add-generic-object"
       validate_certs: "{{ api_validate_cert }}"
       method: POST
       body_format: json
       headers :
         X-chkp-sid : "{{ sid }}"
       body: 
             '{ 
               "create" : "com.checkpoint.management.mgmt_blade.objects.CpNetworkObject",
               "name" : "mds20",
               "ipAddress4" : "192.168.233.20",
               "active" : false,
               "mds" : true
             }'
    register: datasource_mds
    notify: "API Publish handlers"
    changed_when: datasource_mds.status == 200

  - name: "Add MDLS object"
    uri:
       url: "https://{{ api_server }}{{ api_base_url }}/add-generic-object"
       validate_certs: "{{ api_validate_cert }}"
       method: POST
       body_format: json
       headers :
         X-chkp-sid : "{{ sid }}"
       body: 
             '{ 
               "create" : "com.checkpoint.management.mgmt_blade.objects.CpNetworkObject",
               "name" : "mdls30",
               "ipAddress4" : "192.168.233.30",
               "active" : false,
               "mds" : true,
               "mdBladeSettings" : { "serverType" : "MLM" }, 
               "icon" : "Objects/mlm"
             }'
    register: datasource_mdls
    notify: "API Publish handlers"
    changed_when: datasource_mdls.status == 200
  when:  datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0
#- debug:
#    msg="{{taskoutput}}"