---
- name: "Remove a virtual machine {{ vm_name }}"
  vmware_guest:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: absent
    force: true
  delegate_to: localhost