# Run with extra vars for example: -e "vm_name=mds10 to remove the virtual machine mds10
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.vm_name }}"
        groups: mdsm
        vm_name: "{{ item.vm_name }}"
        target: "{{ item.target }}"
        type: "{{ item.type }}"
      with_items:
      - { vm_name: mds10, target: 192.168.233.10, type: primary_mds }
      - { vm_name: mds20, target: 192.168.233.20, type: secondary_mds }
      - { vm_name: mdls30, target: 192.168.233.30, type: mdls }
      - { vm_name: sgvsx40, target: 192.168.233.40, type: sg }

- name: Remove gaia instance from vSphere
  vars:
    target: mdsm
  hosts: "{{ target }}"
  connection: local
  gather_facts: no
  roles:
    - role: roles/vm_ware_remove_instance