---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.vm_name }}"
        ansible_host: "{{ item.target }}"
        groups: mylab
        vm_name: "{{ item.vm_name }}"
        target: "{{ item.target }}"
        type: "{{ item.type }}"
        ansible_user: "{{ lookup('env','TF_VAR_mgmt_api_user') }}"
        ansible_ssh_pass: "{{ lookup('env','TF_VAR_mgmt_api_password') }}"
      with_items:
      - { vm_name: mds10, target: 192.168.233.10, type: primary_mds }
      - { vm_name: mds20, target: 192.168.233.20, type: secondary_mds }
      - { vm_name: mdls30, target: 192.168.233.30, type: mdls }
      - { vm_name: sgvsx40, target: 192.168.233.40, type: sg }

- name:  Add domains to mds server
  hosts: mds10
  connection: local
  gather_facts: no
  roles:
  - role: roles/chkp_add_mds_mdls
    #connection: httpapi
    state: present