# ansible-playbook 1_chkp_create_mdsm_farm.yml -e "vm_template=cloud03_r81ea"
# optional extra vars
## esxi_hostname= cloud03.local, cloud02.local
## vm_template= cloud03_r81ea, cloud02_r80dot40, cloud03_r80dot40
---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.hostname }}"
        ansible_host: "{{ item.ansible_host }}"
        groups: mdsm
      with_items:
      - { hostname: mds10, ansible_host: 192.168.233.10  }
      - { hostname: mds20, ansible_host: 192.168.233.20  }
      - { hostname: mdls30, ansible_host: 192.168.233.30 }

- name: Configure management API to accept connections from any host
  hosts: mds10
  connection: local
  gather_facts: no
  roles:
    - role: roles/chkp_check_mgmt_api
