# ansible-playbook 1_chkp_create_mdsm_farm.yml -e "vm_template=cloud02_r81ea"
---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.vm_name }}"
        groups: mdsm
        vm_name: "{{ item.vm_name }}"
        target: "{{ item.target }}"
        type: "{{ item.type }}"
        nr: "{{ item.nr }}"
      with_items:
      - { vm_name: mds10, target: 192.168.233.10, type: primary_mds, nr: 10 }
      - { vm_name: mds20, target: 192.168.233.20, type: secondary_mds, nr: 20 }
      - { vm_name: mdls30, target: 192.168.233.30, type: mdls, nr: 30 }
      - { vm_name: sgvsx40, target: 192.168.233.40, type: sg, nr: 40 }

- name: Deploy Primary Multi-Domain Server
  hosts: mdsm
  connection: local
  gather_facts: no
  roles:
    - role: roles/vm_ware_deploy_gaia_instance
      delegate_to: localhost
    - role: roles/chkp_config_gaia
      delegate_to: localhost
