---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.vm_name }}"
        groups: mylab
        vm_name: "{{ item.vm_name }}"
        target: "{{ item.target }}"
        type: "{{ item.type }}"
#      register: inventory
      with_items:
      - { vm_name: mds10, target: 192.168.233.10, type: primary_mds }
      - { vm_name: mds20, target: 192.168.233.20, type: secondary_mds }
      - { vm_name: mdls30, target: 192.168.233.30, type: mdls }
      - { vm_name: sgvsx40, target: 192.168.233.40, type: sg }

- name:  Add domains to mds server
  hosts: mds10
  connection: local
  gather_facts: no
  vars_files: 
    - variables.yml
  roles:
    - role: roles/add_mds_domain
      delegate_to: localhost