---
# Run with extra vars for example: ansible-playbook chkp_create_vnf_cloudguard_edge.yml -e "vm_name=cgedgevnf68 target=192.168.233.68"
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ vm_name }}"
        ansible_host: "{{target}}"
        groups: chkp
        vm_name: "{{ vm_name }}"
        target: "{{ target }}"
        vm_template: cloud02_cg_edge_R80dot20
        esxi_hostname: cloud02.local

- name:  Add Gaia Instance and run FTW
  hosts: "{{ vm_name }}"
  connection: local
  gather_facts: no
  roles:
  - role: roles/vm_ware_deploy_gaia_instance
    delegate_to: localhost