- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.vm_name }}"
        groups: mylab
        vm_name: "{{ item.vm_name }}"
        target: "{{ item.target }}"
        type: "{{ item.type }}"
#      register: inventory
      with_items:
      - { vm_name: smsg60, target: 192.168.233.60, type: smsg }
      - { vm_name: sms61, target: 192.168.233.61, type: sms }
      - { vm_name: se62, target: 192.168.233.62, type: ls_se }
      - { vm_name: sg63, target: 192.168.233.63, type: sg }

#    - debug:
#        msg: "{{ inventory }}"

- name: Deploy Standalone SMS and GW
  hosts: 
    - mylab
  connection: local
  gather_facts: no
  vars_files: 
    - variables.yml
  roles:
    - role: roles/deploy_gaia_instance
      delegate_to: localhost
    - role: roles/config_gaia
      delegate_to: localhost

#- name: Deploy Secondary Multi-Domain Server
#  hosts: mds20
#  connection: local
#  gather_facts: no
#  vars_files: 
#    - variables.yml
#    - mds20-vars.yml
#  roles:
#    - role: roles/deploy_gaia_instance
#      delegate_to: localhost
#    - role: roles/config_gaia
#      delegate_to: localhost
#
#- name: Deploy Multi-Domain Log Server
#  hosts: mdls30
#  connection: local
#  gather_facts: no
#  vars_files: 
#    - variables.yml
#    - mdls30-vars.yml
#  roles:
#    - role: roles/deploy_gaia_instance
#      delegate_to: localhost
#    - role: roles/config_gaia
#      delegate_to: localhost