# use variable vm_name to remove the virtual machine
- name: Remove gaia instance from vSphere
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - variables.yml
  roles:
    - role: roles/remove_gaia_instance
