---
# Run with extra vars for example: ansible-playbook vm_ware_add_gaia_instance.yml -e "vm_name=demo69 target=192.168.233.69 type=sg nr=69 vm_template=cloud03_R81EA"
# Avaliable Options: 
# Type: primary_mds, secondary_mds, mdls, primary_sms, secondary_sms, ls_se, smsg, sg
# vm_template: cloud0x_r80dot40, cloud0x_R81EA
# esxi_hostname: cloud02.local, cloud03.local
# gaia_password: xxxxx
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ vm_name }}"
        ansible_host: "{{target}}"
        groups: chkp
        vm_name: "{{ vm_name }}"
        target: "{{ target }}"
        type: "{{ type }}"

- name:  Add Gaia Instance and run FTW
  hosts: "{{ vm_name }}"
  connection: local
  gather_facts: no
  roles:
  - role: roles/vm_ware_deploy_gaia_instance
    delegate_to: localhost
  - role: roles/chkp_config_gaia