---
<<<<<<< HEAD
# Run with extra vars for example: ansible-playbook vm_ware_add_gaia_instance.yml -e "vm_name=demo69 target=192.168.233.69 type=sg nr=69 vm_template=cloud03_R81EA"
# Avaliable Options: 
# Type: primary_mds, secondary_mds, mdls, primary_sms, secondary_sms, ls_se, smsg, sg
# vm_template: cloud0x_r80dot40, cloud0x_R81EA
# esxi_hostname: cloud02.local, cloud03.local
# gaia_password: xxxxx
=======
# Run with extra vars for example: 
## ansible-playbook vm_ware_add_gaia_instance.yml -e "vm_name=test69 target=192.168.233.69 target_masklen=24 target_gw=192.168.233.254 type=primary_sms nr=69 vm_template=cloud03_r81ea"
# Avaliable Options 
## type= primary_mds, secondary_mds, mdls, primary_sms, secondary_sms, ls_se, smsg, sg
## esxi_hostname= cloud03.local, cloud02.local
## vm_template= cloud03_r81ea, cloud02_r80dot40, cloud03_r80dot40
>>>>>>> 52e9d060c1bac0128c0f5a36c9d45c5e18b0ccbc
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ vm_name }}"
        ansible_host: "{{target}}"
        groups: chkp
        vm_name: "{{ vm_name }}"
        target: "{{ target }}"
        target_masklen: "{{ target_masklen }}"
        target_gw: "{{ target_gw }}"
        type: "{{ type }}"

- name:  Add Gaia Instance and run FTW
  hosts: "{{ vm_name }}"
  connection: local
  gather_facts: no
  roles:
  - role: roles/vm_ware_deploy_instance
    delegate_to: localhost
  - role: roles/chkp_config_gaia