---
 - name: Logout
   uri:
      url: "https://{{ mgmt_server }}/web_api//logout"
      validate_certs: false
      method: POST
      body_format: json
      body: "{}"
      headers : 
        X-chkp-sid : "{{ sid }}"