---
- name: Set timezone in Gaia
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/set-time-and-date"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     headers :
       X-chkp-sid : "{{ sid }}"
     body: { "timezone": "{{ gaia_timezone }}" }