---
# Check if admin user exists and if not add admin users using Gaia API
# Task to add admin users using Gaia API
- name: Check Gaia admin user
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/show-user"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     headers :
       X-chkp-sid : "{{ sid }}"
     #body: "{{ item.user }}"
     body: "{{ gaia_show_user }}"
     status_code: [200, 400]
  #loop: "{{ gaia_show_user }}"
  register: show_user_output

- name: Add Gaia admin user
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/add-user"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     headers :
       X-chkp-sid : "{{ sid }}"
     body: "{{ item.user }}"
  loop: "{{ gaia_add_user }}"
  when: show_user_output['json']['name'] != gaia_user_check