---
# Task to set ip address of interface using Gaia API
- name: "Set ip address on interfaces"
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/set-physical-interface"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     headers :
       X-chkp-sid : "{{ sid }}"
     body: "{{ item.interface }}"
  loop: "{{ gaia_interface }}"