---
- name: Set NTP parameters
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/set-ntp"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     headers :
       X-chkp-sid : "{{ sid }}"
     body: {
            "enabled": true,
            "servers": [
                         {
                             "version": "{{ gaia_ntp_version }}",
                             "type": "primary",
                             "address": "{{ gaia_ntp_pri}}"
                         },
                         {
                             "version": "{{ gaia_ntp_version }}",
                             "type": "secondary",
                             "address": "{{ gaia_ntp_sec}}"
                         }
                       ]
             }