---
- name: Set hostname
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/set-hostname"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     headers :
       X-chkp-sid : "{{ sid }}"
     body: { "name": "{{ hostname }}"}