---
- name: Check for Secondary MDS OR MDLS objects
  connection: httpapi
  checkpoint_object_facts:
    object_filter: "{{ item.name }}"
  register: datasource_MDS_MDLS

- name: Wait up to 15 minutes for SIC service tbe ready to recive certificate {{ item.name }}
  wait_for:
    port: 18221
    host: "{{ item.ip_addr }}"
    timeout: 900
  delegate_to: localhost
  when:  datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0

- name: Add {{ item.server_type }} object {{ item.name }}
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/add-mds"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     headers :
       X-chkp-sid : "{{ sid }}"
     body: 
           '{ 
             
             "name" : "{{ item.name }}",
             "ip-address" : "{{ item.ip_addr }}",
             "server-type" : "{{ item.server_type }}",
             "os" : "{{ item.os }}",
             "hardware" : "{{ item.hardware }}",
             "ip-pool-first" : "{{ item.ip_pool_first }}",
             "ip-pool-last" : "{{ item.ip_pool_last }}",
             "one-time-password" : "{{ item.sic_key }}",
             "version" : "{{ item.version }}",
             "color" : "{{ item.color }}"
           }'
  register: datasource_mds
  changed_when: datasource_mds.status == 200
  when:  datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0

- name: API Publish
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/publish"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     body: '{}'
     headers : 
       X-chkp-sid : "{{ sid }}"
  register: taskid
  changed_when: taskid.status == 200
  when:  datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0

- set_fact:
      task: "{{ taskid.json['task-id'] }}"
  when:  datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0

- name: Check API Publish Task Progress 
  uri:
     url: "https://{{ api_server }}{{ api_base_url }}/show-task"
     validate_certs: "{{ api_validate_cert }}"
     method: POST
     body_format: json
     body: 
           '{ 
             "task-id" :  "{{task}}" 
            }'
     headers:
       X-chkp-sid : "{{ sid }}"
  retries: 20
  delay: 3
  register: taskoutput
  until: taskoutput.json.tasks[0]['progress-percentage'] == 100
  when:  datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0

- debug:
    msg="{{datasource_mds}}"

- name: Wait up to 15 minutes for {{ item.name }} to complete its database sync
  wait_for:
    port: 18210
    host: "{{ item.ip_addr }}"
    timeout: 900
  delegate_to: localhost
  when:  
    - datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0
    - '"mds" in item.name' 

- name: Wait up to 15 minutes for {{ item.name }} to complete its database sync
  wait_for:
    port: 19009
    host: "{{ item.ip_addr }}"
    delay: 120
    timeout: 900
  delegate_to: localhost
  when:  
    - datasource_MDS_MDLS.ansible_facts.checkpoint_objects.total == 0
    - '"mdls" in item.name' 